// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC87-UoagNjdPebfDmIicToHMK7VEsMNZY',
    appId: '1:1034172263393:web:98032b3bfdb8fe209280a0',
    messagingSenderId: '1034172263393',
    projectId: 'interfaz-usuario-39b98',
    authDomain: 'interfaz-usuario-39b98.firebaseapp.com',
    storageBucket: 'interfaz-usuario-39b98.firebasestorage.app',
    measurementId: 'G-R67V007FX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6BYKgiscIpNyIx4Le6wN361Nr-bCu1_Y',
    appId: '1:1034172263393:android:cf64774be0be8bd29280a0',
    messagingSenderId: '1034172263393',
    projectId: 'interfaz-usuario-39b98',
    storageBucket: 'interfaz-usuario-39b98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkN9fAns4k7QiWOPa9CwOLIIdHi0k-KuU',
    appId: '1:1034172263393:ios:de6afa55f6006c6e9280a0',
    messagingSenderId: '1034172263393',
    projectId: 'interfaz-usuario-39b98',
    storageBucket: 'interfaz-usuario-39b98.firebasestorage.app',
    iosBundleId: 'com.example.interfazUsuario',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkN9fAns4k7QiWOPa9CwOLIIdHi0k-KuU',
    appId: '1:1034172263393:ios:de6afa55f6006c6e9280a0',
    messagingSenderId: '1034172263393',
    projectId: 'interfaz-usuario-39b98',
    storageBucket: 'interfaz-usuario-39b98.firebasestorage.app',
    iosBundleId: 'com.example.interfazUsuario',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC87-UoagNjdPebfDmIicToHMK7VEsMNZY',
    appId: '1:1034172263393:web:c6afbf58637666a79280a0',
    messagingSenderId: '1034172263393',
    projectId: 'interfaz-usuario-39b98',
    authDomain: 'interfaz-usuario-39b98.firebaseapp.com',
    storageBucket: 'interfaz-usuario-39b98.firebasestorage.app',
    measurementId: 'G-1LRN001DL3',
  );
}
